Repository babaiyu/indonesian_jokes, pull requests merged in 2022-10, with the labels that each got.

#57 add jokes gilang kharisma
  src/data/GilangKharisma.json
Labels: hacktoberfest-accepted, hacktoberfest, jokes

#58 add: file CoC, lisensi dan perbaikan tahun
  CODE_OF_CONDUCT.md
  LICENSE.md
  src/components/Header.jsx
Labels: documentation, enhancement, hacktoberfest-accepted, hacktoberfest

#59 fix: better workflow + adding my unfunny humour
  CONTRIBUTING.md
  README.md
  assets/preview.png
  src/data/ranggakd.json
Labels: documentation, hacktoberfest-accepted, hacktoberfest, jokes

#60 fix: workflow instruction clearer
  README.md
Labels: documentation, hacktoberfest-accepted, hacktoberfest

#61 add joke bapack2
  src/data/dodyagung.json
Labels: hacktoberfest-accepted, hacktoberfest, jokes

#62 add bapack2 joke xixi
  src/data/dodyagung.json
Labels: hacktoberfest-accepted, hacktoberfest, jokes

#63 Add jokes and improve styles with chakra icons
  package-lock.json
  package.json
  src/App.css
  src/components/Header.jsx
  src/data/andriawan24.json
Labels: enhancement, hacktoberfest-accepted, hacktoberfest, jokes

#64 Update my jokes, xixixi
  src/data/babaiyu.json
Labels: hacktoberfest-accepted, hacktoberfest, jokes

#65 Dockerize the web app 🛠
  Dockerfile
Labels: enhancement, hacktoberfest-accepted, hacktoberfest

#66 Update React18, Update Change Theme
  src/App.jsx
  src/helpers/LazyLoad.jsx
  src/hooks/useDarkMode.js
  src/main.jsx
Labels: enhancement, hacktoberfest-accepted, hacktoberfest

#67 fix Divider not visible in Light theme
  src/App.jsx
  src/components/Footer.jsx
  src/components/Home.jsx
Labels: enhancement, hacktoberfest-accepted, hacktoberfest

#68 Fix intervention issue
  generate.js
  src/components/Footer.jsx
  src/components/ListItem.jsx
Labels: enhancement, hacktoberfest-accepted, hacktoberfest

#69 [update] added new jokes
  src/data/bayue48.json
Labels: hacktoberfest-accepted, hacktoberfest, jokes

#70 Create docker compose
  .dockerignore
  Dockerfile
  docker-compose.yml
Labels: enhancement, hacktoberfest-accepted, hacktoberfest

#71 Added new Jokes
  src/data/rizkypur.json
Labels: hacktoberfest-accepted, hacktoberfest, jokes

#73 add:jokes_honestyan
  src/data/honestyan.json
Labels: hacktoberfest-accepted, hacktoberfest, jokes

#74 Add new jokes by bojjidev
  src/data/bojjidev.json
Labels: hacktoberfest-accepted, hacktoberfest, jokes

#75 add: new jokes marde12345
  src/data/marde12345.json
Labels: hacktoberfest-accepted, hacktoberfest, jokes

#76 add new jokes rizanw
  src/data/rizanw.json
Labels: hacktoberfest-accepted, hacktoberfest, jokes
